### ISSUE TITLE
Whitelisting a subclaim from the ID token

### ISSUE THREAD

**Issue by MarieComon** [OpenIDC/mod_auth_openidc#432]
This is a feature request to support whitelisting a specific subclaim from the ID token and set it as an Apache environment variable. Then this subclaim could be set in a HTTP header. 

Use the following configurations: 
OIDCPassClaimsAs environment 
OIDCClaimPrefix OIDC_ 
OIDCPassIDTokenAs claims 
OIDCWhiteListedClaims claim1 claim2 claim3   

###### Minimized example
A token with the following structure : 
{ 
    "claim1": "val1", 
    "claim2": { 
        "subclaim1": "val" 
    }, 
    "claim3": "val3" 
} 

###### Expected behaviour
Whitelisting only a subclaim (here "subclaim1") instead of the whole claim (here "claim2").

**Comment by zandbelt** [comment]
support for doing all kinds of filtering/processing of claims - including subclaims - before storing them in the session is implemented with `OICFilterClaimsExpr` , see: https://github.com/OpenIDC/mod_auth_openidc/commit/8067246a3fe1bd5aa077f92164cbb2cb1092cd1b
